Revert "Update CMake from 3.0.1 to 3.1.0-rc3 for nightly build" on MacOSX
This commit restore building of Slicer by partially reverting
commit b01192bed so that CMake 3.0.1 is still used on MacOSX.

The build of vtkGUISupportQt library failed with the following error:

$ make vtkGUISupportQt/fast VERBOSE=1
[...]
error: error reading '/Users/kitware/Dashboards/Support/qt-everywhere-opensource-build-4.8.6/lib/QtGui.framework/Headers'

Full details are reported in the file "factory-error-using-cmake-3.1.0-rc3.txt"
for future reference.