Add scripts allowing to update the module/extension listing on Slicer wiki
Note that on MacOSX, a warkaround to address commontk/AppLauncher#57 has
been added.

Note that it is currently disabled on windows. Bootstrapping of pip does
not work yet. It fails with the following error:

// -------
C:\D\Support\slicer-wiki-scripts>C:\D\P\Slicer-440-package\Slicer-build\Slicer.exe --launch python.exe get-pip.py
Traceback (most recent call last):
  File "get-pip.py", line 19862, in <module>
    main()
  File "get-pip.py", line 152, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip
  File "c:\users\kitware\appdata\local\temp\tmpsuhtdv\pip.zip\pip\__init__.py", line 13, in <module>
  File "c:\users\kitware\appdata\local\temp\tmpsuhtdv\pip.zip\pip\utils\__init__.py", line 18, in <module>
  File "c:\users\kitware\appdata\local\temp\tmpsuhtdv\pip.zip\pip\locations.py", line 207, in <module>
  File "c:\users\kitware\appdata\local\temp\tmpsuhtdv\pip.zip\pip\utils\appdirs.py", line 183, in site_config_dirs
  File "c:\users\kitware\appdata\local\temp\tmpsuhtdv\pip.zip\pip\utils\appdirs.py", line 224, in _get_win_folder_from_registry
WindowsError: [Error 2] The system cannot find the file specified
// -------