Fix exception when running slicer-publish-*-metadata script as cronjob
When running as cronjob, a minimal env is used and it is required to
manually set the USER env variable.

This commit will fix error like the following one:

8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---
[...]
Saved '/tmp/slicer-packages-metadata/metadata/slicer-extension-modules_4.4_Linux.json'
Traceback (most recent call last):
  File "slicer_wiki_extension_module_listing.py", line 1677, in <module>
    args.action(args)
  File "slicer_wiki_extension_module_listing.py", line 1217, in _saveAllExtensionsModulesMetadata
    slicerVersion=args.slicer_version)
  File "slicer_wiki_extension_module_listing.py", line 1202, in saveAllExtensionsModulesMetadata
    index.commit(msg)
  File "/home/kitware/Dashboards/Package/Slicer-440-package/python-install/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/index/base.py", line 887, in commit
    return Commit.create_from_tree(self.repo, tree, message, parent_commits, head)
  File "/home/kitware/Dashboards/Package/Slicer-440-package/python-install/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/objects/commit.py", line 302, in create_from_tree
    committer = Actor.committer(cr)
  File "/home/kitware/Dashboards/Package/Slicer-440-package/python-install/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/util.py", line 354, in committer
    return cls._main_actor(cls.env_committer_name, cls.env_committer_email, config_reader)
  File "/home/kitware/Dashboards/Package/Slicer-440-package/python-install/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/util.py", line 327, in _main_actor
    default_email = get_user_id()
  File "/home/kitware/Dashboards/Package/Slicer-440-package/python-install/lib/python2.7/site-packages/GitPython-0.3.2.RC1-py2.7.egg/git/util.py", line 120, in get_user_id
    username = os.getlogin()
OSError: [Errno 22] Invalid argument
8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---